# Generated by Django 4.2.1 on 2023-05-19 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_otp_created_at_alter_otpuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 18, 6, 525280, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='otpuser',
            name='secret_key',
            field=models.CharField(default='PKA57Q4M4EFOOKM2E3XBKWLJGRSPQICM', max_length=32),
        ),
    ]
