# Generated by Django 4.2.1 on 2023-05-19 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_alter_otp_created_at_alter_otpuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='otpuser',
            name='secret_key',
            field=models.CharField(default='XDCKTFBMDXNWUDPAAGECXDC2GNFDLKCD', max_length=32),
        ),
    ]
