# Generated by Django 4.2.1 on 2023-05-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_alter_otp_created_at_alter_otpuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpuser',
            name='secret_key',
            field=models.CharField(default='42ZR4BYOHZXHQORDZZYV3KRMO7AMAWBQ', max_length=32),
        ),
    ]
