# Generated by Django 4.2.1 on 2023-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_alter_otpuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpuser',
            name='secret_key',
            field=models.CharField(default='NMISIDEUU5LL4O5OEHJYAJXAUYBWPAZT', max_length=32),
        ),
    ]
